task-5
Gavrilajava/go_gavrila pull request #4
Opened 2023-07-10 01:24 UTC by Gavrilajava

2023-07-10 01:38 UTC, Gavrilajava commented on task-5/pkg/index/index.go
> +	content_storage, err := os.OpenFile(content_path, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0666)
The last parameter really drove me bonkers. I'm sure there is a way to make it OS-independent, but I'm giving up for now. By the way, it is an octal notation of an integer. The leading 0 doesn't affect any access, it simply indicates the notation.

2023-07-10 01:45 UTC, Gavrilajava commented on task-5/pkg/index/index.go
> +		}
is there a way to shorten 4 lines of code from above? I've tried "for line, err := reader.ReadString('\n'); err != nil {}"but it doesn't work.

2023-07-11 18:25 UTC, DmitriyVTitov requested changes
Нужно учиться работать с ошибками. Читайте статьи и учебники.
Ну и имена функций следует писать как принято.

2023-07-11 18:25 UTC, DmitriyVTitov commented on task-5/pkg/index/index.go
> +func load_file(name string) []string {
мы пишем не на Си, функции надо называть в camelCase

2023-07-11 18:25 UTC, DmitriyVTitov commented on task-5/pkg/index/index.go
> +	}
Функция, работающая с вводом-выводом не может не возвращать ошибку!
Напечатать что-то на экране не достаточно. Ошибку надо возвращать.
Как по этой функции понять: это у меня файл пустой или его не существует вообще?

2023-07-11 18:25 UTC, DmitriyVTitov commented on task-5/pkg/index/index.go
> +		}
Если произошла ошибка, то наплевать? Просто прервать цикл и вернуть что получилось?
Так нельзя, ошибку надо возвращать!

2023-07-11 18:25 UTC, DmitriyVTitov commented on task-5/pkg/index/index.go
> +}
странная функция

2023-07-16 19:40 UTC, closed without merging