Task 5v2
Gavrilajava/go_gavrila pull request #6
Opened 2023-07-16 19:41 UTC by Gavrilajava

2023-07-16 19:51 UTC, Gavrilajava commented on task-5/pkg/index/index.go
> +		s.Documents = append(s.Documents, link)
The line above does not work if s is a reference. Could you please delve deeper into this topic here or in one of the lessons? I would like to understand why can  I add an element to a map, but I cannot to a slice if both are references.

2023-07-19 09:14 UTC, DmitriyVTitov requested changes

2023-07-19 09:14 UTC, DmitriyVTitov commented on task-5/cmd/gosearch.go
> +	} else {
Реакцией на ошибку ОБЯЗАНО быть действие.
Я это уже, наверное, не меньше 100 раз написал при проверке ДЗ. Даже в Телеграме писал.
Так не могу принять.

2023-07-22 11:06 UTC, DmitriyVTitov approved these changes
ОК

2023-07-22 11:06 UTC, DmitriyVTitov commented on task-5/pkg/index/index.go
> +		s.Documents = append(s.Documents, link)
Функция `append` при превышении ёмкости слайса создаёт новый слайс и его нужно присвоить оригинальному. То есть append не работает "по месту", она создаёт новые указатели на слайсы. А добавление в `map` не меняет оригинальный указатель на саму структуру.
Я рассказывал об устройстве слайсов и массивов на занятии №4. Вот код на эту тему.
```
package main

import "fmt"

func main() {
	slice := []int{1, 2, 3}
	fmt.Println(slice)
	fmt.Println(addToCopy(slice))
	fmt.Println(slice)
	fmt.Println(addToOriginal(&slice))
	fmt.Println(slice)
}

func addToCopy(s []int) []int {
	return append(s, 1, 2, 3)
}

func addToOriginal(s *[]int) []int {
	*s = append(*s, 1, 2, 3)
	return *s
}
```

2023-07-22 11:06 UTC, DmitriyVTitov commented on task-5/cmd/gosearch.go
> +		if index.Empty() {
Для чего тут `else`? Мало того, что он не имеет смысла, так и вообще: удачная ветка исполнения должна быть максимально слева в коде.

2023-07-22 20:07 UTC, merged